[package]
name = "signal-kit"
version = "0.1.0"
edition = "2024"

[dependencies]
rustfft = "6.2.0"
num-complex = "0.4"
num-traits = "0.2.19"
rand = "0.8"
wide = "0.8.1"
bimap = "0.6.3"
bytemuck = "1.24"

[dev-dependencies]
plotly = "0.13"
